"""10:53

Revision ID: 02772e991b8e
Revises: 9393d97193fa
Create Date: 2024-11-29 10:53:27.582730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02772e991b8e'
down_revision = '9393d97193fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String))

    # ### end Alembic commands ###
