"""transport details added

Revision ID: 0c7ec8cc18ef
Revises: 95f049513988
Create Date: 2024-11-19 14:00:30.239374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7ec8cc18ef'
down_revision = '95f049513988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_company', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transport_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transport_costs', sa.String(), nullable=True))
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('transport_costs')
        batch_op.drop_column('transport_type')
        batch_op.drop_column('transport_company')

    # ### end Alembic commands ###
