"""company model fixed

Revision ID: 1c27224d1c4e
Revises: 7c54c7ee4ef5
Create Date: 2024-11-19 16:17:56.588254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c27224d1c4e'
down_revision = '7c54c7ee4ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('companies.id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_constraint('pipelines.id', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
