"""11:26

Revision ID: 508c5389754a
Revises: 1c27224d1c4e
Create Date: 2024-11-25 11:27:12.140303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508c5389754a'
down_revision = '1c27224d1c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registration_number')

    # ### end Alembic commands ###
