"""pipeline management updates

Revision ID: 7c54c7ee4ef5
Revises: 0c7ec8cc18ef
Create Date: 2024-11-19 15:09:03.650360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7c54c7ee4ef5'
down_revision = '0c7ec8cc18ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pipeline_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('pipelines.id', 'pipelines', ['pipeline_id'], ['id'])
        batch_op.drop_column('pipeline_type')
        batch_op.drop_column('last_inspection_date')
        batch_op.drop_column('pipeline_location')
        batch_op.drop_column('pipeline_status')
        batch_op.drop_column('maintenance_records')
        batch_op.drop_column('pipeline_capacity')
        batch_op.drop_column('weight_capacity')
        batch_op.drop_column('next_inspection_date')
        batch_op.drop_column('installed_date')
        batch_op.drop_column('custom_fields')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('installed_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('next_inspection_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('weight_capacity', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_capacity', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_records', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_location', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_inspection_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pipeline_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pipeline_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
