"""employee_id column dropped

Revision ID: a45a93b6bff2
Revises: b329567855f1
Create Date: 2024-11-29 16:10:55.057005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45a93b6bff2'
down_revision = 'b329567855f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
