"""unique constraints removed from User

Revision ID: b329567855f1
Revises: 02772e991b8e
Create Date: 2024-11-29 16:04:43.726766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b329567855f1'
down_revision = '02772e991b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR()))
        batch_op.add_column(sa.Column('social_security_number', sa.VARCHAR()))

    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
