"""Add unique_id to Folder

Revision ID: bd4699f80c27
Revises: d15b7939f202
Create Date: 2024-11-30 20:16:27.214559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4699f80c27'
down_revision = 'd15b7939f202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.BigInteger(), nullable=False))
        batch_op.create_index(batch_op.f('ix_folders_unique_id'), ['unique_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_unique_id'))
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
