"""16:21

Revision ID: d15b7939f202
Revises: a45a93b6bff2
Create Date: 2024-11-29 16:22:20.311789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15b7939f202'
down_revision = 'a45a93b6bff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_security_number', sa.String()))

    # ### end Alembic commands ###
